version: "3.7"
services:
  app:
    build:
      args:
        user: sentiment-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sentiment
    container_name: sentiment-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sentiment

  nginx:
    image: nginx:alpine
    container_name: sentiment-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - sentiment

networks:
  sentiment:
    driver: bridge
